version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - pg-data:/var/lib/postegresql/data
    environment:
      POSTGRES_USER: votacao
      POSTGRES_PASSWORD: _Votacao
      POSTGRES_DB: db_votacao
    ports:
      - "5441:5432"
  sonarqube:
    image: sonarqube:10.0.0-community
    command: -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m
    restart: unless-stopped
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    networks:
      - sonar-net
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5435/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - /home/ubuntu/sonar-data/data:/opt/sonarqube/data
      - /home/ubuntu/sonar-data/extensions:/opt/sonarqube/extensions
      - /home/ubuntu/sonar-data/logs:/opt/sonarqube/logs
  sonarqube_db:
    image: postgres
    container_name: sonarqube_db
    restart: unless-stopped
    ports:
      - "5435:5432"
    networks:
      - sonar-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /home/ubuntu/postgres/postgresql:/var/lib/postgresql
      - /home/ubuntu/postgres/data:/var/lib/postgresql/data
#  app:
#    image: votacao:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#    ports:
#      - "8083:8083"
#    environment:
#      SPRING_DATASOURCE_URL: r2dbc:postgresql://localhost:5441/db_votacao
#      SPRING_DATASOURCE_FLYAWAY_URL: jdbc:postgresql://localhost:5441/db_votacao
#      SPRING_DATASOURCE_USERNAME: votacao
#      SPRING_DATASOURCE_PASSWORD: _Votacao
#      SPRING_PROFILES_ACTIVE: dev
#      APP-ENDPOINT-BASE: http://localhost:8083
volumes:
  pg-data:
  sonar-data:
  sonarqube_db:
networks:
  sonar-net:
    external: false