info:
  app:
    name: @project.name@
    artifactId: @project.artifactId@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@
server:
  port: 8083
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    configUrl: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /v3/api-docs
    enabled: true
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    defaultModelsExpandDepth: -1
management:
  endpoint:
    health:
      show-details: never
      cache:
        time-to-live: "30s"
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  main:
    lazy-initialization: false
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      minimumIdle: 1
      idleTimeout: 10000
      connectionTimeout: 30000
      maximumPoolSize: 20
      maxLifetime: 30000
r2dbc:
  migrate:
    resources-paths: classpath:/db/migration/*.sql